const exercises=[
{title:"La cuadrícula del tesoro",level:"Nivel 1 · Matrices",context:"Un pirata tiene un mapa de 8 × 8 posiciones. Todas empiezan vacías y debes esconder un único tesoro en una posición aleatoria.",objective:"Consolidar la creación, inicialización, recorrido e impresión de una matriz bidimensional.",task:"Crea una matriz 8 × 8, rellénala con '.', coloca una 'T' en una posición aleatoria y muestra el mapa.",requirements:["Dimensionar una matriz 8 × 8.","Rellenar todas las posiciones con '.'.","Generar fila y columna con Azar().","Colocar exactamente una 'T'.","Imprimir la matriz correctamente."],concepts:["Dimension","Para anidado","Azar()","Caracter","Escribir Sin Saltar"],reflection:"¿Por qué necesitamos dos bucles Para para rellenar toda la matriz?",hint:"Un Para recorre las filas y otro, dentro, las columnas. Para obtener 1..8: Azar(8) + 1.",solution:"Algoritmo CuadriculaTesoro\n    Dimension tablero[8,8]\n    Para fila=1 Hasta 8 Hacer\n        Para columna=1 Hasta 8 Hacer\n            tablero[fila,columna]='.'\n        FinPara\n    FinPara\n    f=Azar(8)+1\n    c=Azar(8)+1\n    tablero[f,c]='T'\nFinAlgoritmo"},
{title:"Campo de minas",level:"Nivel 2 · Azar sin repetir",context:"Debes generar un campo de 10 × 10 y colocar 10 minas sin que dos ocupen la misma celda.",objective:"Aprender a buscar una posición libre usando Repetir...Hasta Que.",task:"Inicializa un tablero 10 × 10 con '.' e inserta exactamente 10 minas 'M' sin repetir posiciones.",requirements:["Matriz 10 × 10.","10 minas exactas.","Evitar posiciones repetidas.","Usar Repetir...Hasta Que.","Mostrar el tablero."],concepts:["Repetir","Hasta Que","Azar()","Comparación","Matrices"],reflection:"¿Qué problema habría si escribiéramos una mina sin comprobar antes la celda?",hint:"Repite la generación mientras no encuentres una posición con '.'.",solution:"Algoritmo CampoMinas\n    Dimension tablero[10,10]\n    Para f=1 Hasta 10 Hacer\n        Para c=1 Hasta 10 Hacer\n            tablero[f,c]='.'\n        FinPara\n    FinPara\n    Para i=1 Hasta 10 Hacer\n        Repetir\n            f=Azar(10)+1\n            c=Azar(10)+1\n        Hasta Que tablero[f,c]=='.'\n        tablero[f,c]='M'\n    FinPara\nFinAlgoritmo"},
{title:"Invasión alienígena",level:"Nivel 3 · Varios elementos",context:"Una cuadrícula espacial debe contener aliens y naves sin que ningún elemento ocupe una posición usada.",objective:"Generalizar la inserción aleatoria sin repetición para varios tipos de elementos.",task:"Crea una cuadrícula 10 × 10 con '.', coloca 8 aliens 'A' y 5 naves 'N' sin solapamientos.",requirements:["Inicializar con '.'.","Insertar 8 A.","Insertar 5 N.","Comprobar posición libre.","Mostrar la matriz."],concepts:["Para","Repetir","Azar()","Caracter","Estado de celda"],reflection:"¿Por qué podemos utilizar la misma condición de posición libre para aliens y naves?",hint:"Los dos tipos pueden buscar una celda cuyo contenido siga siendo '.'.",solution:"Algoritmo Invasion\n    Dimension espacio[10,10]\n    // Inicializar con '.'\n    // Insertar 8 A buscando hueco\n    // Insertar 5 N buscando hueco\nFinAlgoritmo"},
{title:"Contar objetos",level:"Nivel 4 · Contadores",context:"Ahora no basta con construir la matriz: debes recorrerla para obtener información.",objective:"Diferenciar creación y análisis de datos usando un contador.",task:"Genera una matriz 10 × 10 con 15 letras 'A' sin repetir y después cuenta cuántas A existen.",requirements:["Insertar 15 A.","Inicializar contadorA.","Recorrer toda la matriz.","Incrementar solo al encontrar A.","Mostrar el total."],concepts:["Contador","Si","Recorrido completo","Matrices","Azar()"],reflection:"¿Dónde debes inicializar contadorA y por qué?",hint:"Inicializa contadorA=0 antes del recorrido de análisis.",solution:"Algoritmo ContarObjetos\n    contadorA=0\n    Para f=1 Hasta 10 Hacer\n        Para c=1 Hasta 10 Hacer\n            Si tablero[f,c]=='A' Entonces\n                contadorA=contadorA+1\n            FinSi\n        FinPara\n    FinPara\nFinAlgoritmo"},
{title:"Buscar a Homer",level:"Nivel 5 · Búsqueda",context:"Una sopa de letras contiene varios Homer representados por H. Debes localizarlos y mostrar sus coordenadas.",objective:"Practicar recorridos de búsqueda y coordenadas fila/columna.",task:"Crea una matriz 10 × 10 con '*', inserta 10 'H' sin repetir y muestra fila y columna de cada Homer.",requirements:["Inicializar con '*'.","Insertar 10 H.","Recorrer toda la matriz.","Detectar cada H.","Mostrar coordenadas."],concepts:["Búsqueda","Si","Coordenadas","Para anidado","Repetir"],reflection:"¿Qué diferencia hay entre insertar los Homer y buscarlos?",hint:"Primero construyes los datos; después haces otro recorrido para analizarlos.",solution:"Algoritmo BuscarHomer\n    Para f=1 Hasta 10 Hacer\n        Para c=1 Hasta 10 Hacer\n            Si sopa[f,c]=='H' Entonces\n                Escribir 'Homer en fila ',f,' columna ',c\n            FinSi\n        FinPara\n    FinPara\nFinAlgoritmo"},
{title:"Aparcamiento",level:"Nivel 6 · Análisis global",context:"Un parking de 5 filas y 8 plazas necesita controlar libres y ocupadas.",objective:"Combinar generación aleatoria, contadores y análisis completo.",task:"Usa 'L' para libre y 'O' para ocupada. Ocupa 15 plazas aleatoriamente y calcula libres y ocupadas.",requirements:["Matriz 5 × 8.","Inicializar con L.","15 O sin repetir.","Contar L y O.","Mostrar parking y totales."],concepts:["Contadores","Matriz rectangular","Azar()","Repetir","Si"],reflection:"Si sabemos que hay 40 plazas y ocupamos 15, ¿por qué sigue siendo útil recorrer la matriz?",hint:"Usa dos contadores en el recorrido final: libres y ocupadas.",solution:"Algoritmo Parking\n    libres=0\n    ocupadas=0\n    Para f=1 Hasta 5 Hacer\n        Para c=1 Hasta 8 Hacer\n            Si parking[f,c]=='O' Entonces\n                ocupadas=ocupadas+1\n            Sino\n                libres=libres+1\n            FinSi\n        FinPara\n    FinPara\nFinAlgoritmo"},
{title:"Hotel por plantas",level:"Nivel 7 · Contadores por fila",context:"Un hotel de 6 plantas y 5 habitaciones necesita conocer la ocupación de cada planta.",objective:"Aprender a reiniciar contadores en el nivel correcto de un bucle anidado.",task:"Ocupa 12 habitaciones aleatoriamente y muestra cuántas ocupadas hay en cada planta.",requirements:["Matriz 6 × 5.","12 ocupadas.","Contador global.","Contador por planta.","Reiniciar contadorPlanta correctamente."],concepts:["Contador local","Contador global","Para anidado","Reinicio"],reflection:"¿Qué ocurriría si contadorPlanta=0 estuviera antes del bucle de filas?",hint:"Reinícialo justo al comenzar cada nueva fila.",solution:"Algoritmo Hotel\n    Para f=1 Hasta 6 Hacer\n        contadorPlanta=0\n        Para c=1 Hasta 5 Hacer\n            Si hotel[f,c]=='O' Entonces\n                contadorPlanta=contadorPlanta+1\n            FinSi\n        FinPara\n        Escribir 'Planta ',f,': ',contadorPlanta\n    FinPara\nFinAlgoritmo"},
{title:"Carrera de coches",level:"Nivel 8 · Entrada + validación",context:"Hay 5 coches escondidos en un circuito 10 × 10. El usuario consulta una coordenada.",objective:"Combinar matrices, entrada de usuario y validación de límites.",task:"Coloca 5 coches 'C'. Pide fila y columna, valida que estén entre 1 y 10 y muestra si hay coche o está libre.",requirements:["5 coches sin repetir.","Leer fila y columna.","Validar límites.","Consultar solo si son válidos.","Mostrar resultado."],concepts:["Leer","Condición compuesta","Y","Validación","Acceso directo"],reflection:"¿Por qué debemos validar antes de consultar tablero[fila,columna]?",hint:"Comprueba los cuatro límites antes de acceder a la matriz.",solution:"Algoritmo Carrera\n    Leer f\n    Leer c\n    Si f>=1 Y f<=10 Y c>=1 Y c<=10 Entonces\n        Si tablero[f,c]=='C' Entonces\n            Escribir 'Hay un coche'\n        Sino\n            Escribir 'Libre'\n        FinSi\n    Sino\n        Escribir 'Coordenadas no válidas'\n    FinSi\nFinAlgoritmo"},
{title:"Batalla naval",level:"Nivel 9 · Cambio de estado",context:"Un tablero contiene 5 barcos ocultos y el jugador dispone de 5 disparos.",objective:"Representar cambios de estado modificando el contenido de una celda.",task:"Crea un tablero 8 × 8 con agua '~' y 5 barcos 'B'. En cada acierto cambia B por X y cuenta impactos.",requirements:["5 barcos sin repetir.","5 disparos.","Validar coordenadas.","Cambiar B por X.","Contar impactos."],concepts:["Estado","Actualización","Para","Si","Contador"],reflection:"¿Por qué debemos cambiar B por X cuando se acierta?",hint:"La celda debe reflejar que ese barco ya ha sido alcanzado.",solution:"Algoritmo BatallaNaval\n    impactos=0\n    Para disparo=1 Hasta 5 Hacer\n        Leer f\n        Leer c\n        Si tablero[f,c]=='B' Entonces\n            tablero[f,c]='X'\n            impactos=impactos+1\n        FinSi\n    FinPara\nFinAlgoritmo"},
{title:"Parque de atracciones",level:"Nivel 10 · Integración",context:"Diseña un parque 10 × 10 con atracciones, restaurantes y baños distribuidos aleatoriamente.",objective:"Integrar matrices, azar, no repetición, contadores, análisis por fila y consulta de coordenadas.",task:"Coloca 10 A, 5 R y 3 B sin solapamientos. Cuenta cada tipo, analiza una fila elegida y consulta una coordenada.",requirements:["10 × 10 con '.'.","10 A, 5 R, 3 B sin repetir.","Contar los tres tipos.","Analizar una fila.","Consultar una coordenada válida."],concepts:["Integración","Matrices","Azar()","Repetir","Contadores","Validación","Si/SiNo"],reflection:"¿Qué partes pertenecen a construcción de datos y cuáles a análisis?",hint:"Divide el algoritmo: inicializar → insertar → mostrar → contar → analizar fila → consultar coordenada.",solution:"Algoritmo Parque\n    Dimension parque[10,10]\n    // 1. Inicializar\n    // 2. Insertar A, R y B sin repetir\n    // 3. Contar y mostrar\n    // 4. Analizar una fila\n    // 5. Consultar una coordenada\nFinAlgoritmo"}
];
const quiz=[
["¿Qué tipo utilizarías para almacenar 27?",["Real","Entero","Logico","Caracter"],1,"27 es un número entero."],
["¿Qué tipo utilizarías para almacenar 3.75?",["Entero","Caracter","Real","Logico"],2,"Tiene parte decimal: Real."],
["¿Qué tipo corresponde mejor a 'A'?",["Caracter","Cadena","Entero","Logico"],0,"Una sola letra es un Caracter."],
["¿Cuál es un valor válido para Logico?",["Hola","23","Verdadero","A"],2,"Logico usa Verdadero/Falso."],
["¿Qué crea Dimension tablero[10,10]?",["Un Real","Una matriz","Un bucle","Una condición"],1,"Dos índices representan una matriz."],
["¿Cuántas posiciones tiene 10 × 10?",["10","20","100","1000"],2,"10 × 10 = 100."],
["¿Por qué dos Para para recorrer una matriz?",["Tipos","Filas y columnas","Azar","No hacen falta"],1,"Uno recorre filas y otro columnas."],
["¿Cuántas iteraciones hace Para fila=1 Hasta 10?",["9","10","11","Infinitas"],1,"Recorre 1 hasta 10."],
["Dos bucles de 1 a 10 anidados ejecutan el interior...",["10","20","100","1000"],2,"10 × 10 = 100."],
["Azar(10) produce aproximadamente...",["0 a 9","Siempre 10","1 a 10","Una letra"],0,"Por eso suele sumarse 1."],
["¿Por qué Azar(10)+1?",["Obtener 1..10","Obtener 10","Porque es obligatorio","Obtener reales"],0,"Desplaza el rango."],
["¿Para qué sirve Repetir...Hasta Que al insertar?",["Imprimir","Buscar posición válida","Dimensionar","Convertir"],1,"Repite hasta cumplir la condición."],
["Hasta Que tablero[f,c]=='*' busca...",["Ocupada","Libre con *","Última","[1,1]"],1,"Solo acepta posiciones con *."],
["Comprobar que una posición está libre evita...",["Filas","Solapamientos","Números","Bucles"],1,"Evita sobrescribir otro elemento."],
["Escribir Sin Saltar sirve para...",["Borrar","Imprimir sin salto automático","Generar Azar","Cambiar fila"],1,"Permite imprimir columnas en la misma línea."],
["Escribir vacío después de las columnas sirve para...",["Cambiar de línea","Borrar","Generar columna","Terminar"],0,"Separa las filas."],
["Antes de contadorH=contadorH+1 debemos...",["Nada","Inicializar contadorH","Usar Azar","Crear otra matriz"],1,"Un contador necesita valor inicial."],
["Inicialización típica de un contador:",["contador=contador+1","contador=0","contador=Verdadero","contador='*'"],1,"Los contadores suelen empezar en 0."],
["Si toda la matriz contiene 'L' y buscamos '*' con Repetir...",["Termina","Puede no terminar","Convierte L","PSeInt crea *"],1,"La condición nunca se cumple."],
["Orden más lógico:",["Imprimir→crear","Crear→rellenar→insertar→analizar→mostrar","Azar→Fin","Mostrar→Dimension"],1,"Primero construimos y después analizamos."]
];
const KEY="pseint-site-v1";
let state=JSON.parse(localStorage.getItem(KEY)||"null")||{current:0,done:{},drafts:{},answers:{},checks:{},quiz:{},quizDone:false};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(KEY,JSON.stringify(state));progress();renderNav()}
function show(id){$$(".view").forEach(v=>v.classList.remove("active"));$("#"+id).classList.add("active");if(innerWidth<901)$(".sidebar").classList.remove("open");scrollTo({top:0,behavior:"smooth"})}
function renderNav(){$("#nav").innerHTML="";exercises.forEach((e,i)=>{const b=document.createElement("button");b.className="navbtn "+(state.done[i]?"done ":"")+(state.current===i&&$("#exercise").classList.contains("active")?"active":"");b.innerHTML=String(i+1).padStart(2,"0")+" <span>"+e.title+"<small>"+e.level+"</small></span>";b.onclick=()=>openEx(i);$("#nav").appendChild(b)});$("#quizNav").classList.toggle("done",state.quizDone)}
function progress(){const n=Object.values(state.done).filter(Boolean).length+(state.quizDone?1:0),p=Math.round(n/11*100);$("#pct").textContent=p+"%";$("#bar").style.width=p+"%";$("#detail").textContent=n+" de 11 bloques completados"}
function openEx(i){state.current=i;save();renderEx();show("exercise")}
function renderEx(){const e=exercises[state.current],i=state.current;$("#pageTitle").textContent="Ejercicio "+String(i+1).padStart(2,"0");$("#level").textContent=e.level;$("#title").textContent=e.title;$("#context").textContent=e.context;$("#objective").textContent=e.objective;$("#task").textContent=e.task;$("#requirements").innerHTML=e.requirements.map(x=>"<li>"+x+"</li>").join("");$("#concepts").innerHTML=e.concepts.map(x=>"<span>"+x+"</span>").join("");$("#reflection").textContent=e.reflection;$("#hint").textContent=e.hint;$("#solution").textContent=e.solution;$("#status").textContent=state.done[i]?"✓ Completado":(i+1)+" / 10";$("#editor").value=state.drafts[i]||"";$("#answer").value=state.answers[i]||"";$$("[data-check]").forEach(c=>c.checked=!!(state.checks[i]||{})[c.dataset.check]);$("#hintBox").classList.add("hidden");$("#solutionBox").classList.add("hidden");$("#prev").disabled=i===0;$("#next").textContent=i===9?"Ir al test →":"Siguiente →";$("#complete").textContent=state.done[i]?"✓ Ejercicio completado":"Marcar completado";renderNav()}
$("#editor").oninput=e=>{state.drafts[state.current]=e.target.value;save()};$("#answer").oninput=e=>{state.answers[state.current]=e.target.value;save()};
$$("[data-check]").forEach(c=>c.onchange=e=>{state.checks[state.current]||={};state.checks[state.current][e.target.dataset.check]=e.target.checked;save()});
$("#hintBtn").onclick=()=>{$("#hintBox").classList.toggle("hidden");$("#hintBtn").textContent=$("#hintBox").classList.contains("hidden")?"Ver pista":"Ocultar pista"};
$("#solutionBtn").onclick=()=>{$("#solutionBox").classList.toggle("hidden");$("#solutionBtn").textContent=$("#solutionBox").classList.contains("hidden")?"Ver solución":"Ocultar solución"};
$("#complete").onclick=()=>{state.done[state.current]=!state.done[state.current];save();renderEx()};
$("#prev").onclick=()=>state.current>0&&openEx(state.current-1);$("#next").onclick=()=>state.current<9?openEx(state.current+1):(renderQuiz(),show("quiz"),$("#pageTitle").textContent="Test final");
$("#start").onclick=()=>openEx(0);$("#continue").onclick=()=>openEx(state.current||0);$("#quizNav").onclick=()=>{renderQuiz();show("quiz");$("#pageTitle").textContent="Test final"};$("#menu").onclick=()=>$(".sidebar").classList.toggle("open");
$("#copy").onclick=async()=>{try{await navigator.clipboard.writeText($("#editor").value);$("#copy").textContent="Copiado";setTimeout(()=>$("#copy").textContent="Copiar",1000)}catch{}};
function renderQuiz(){$("#quizList").innerHTML="";quiz.forEach((q,i)=>{const a=document.createElement("article");a.className="qcard";a.dataset.i=i;a.innerHTML='<div class="qtitle">'+(i+1)+'. '+q[0]+'</div><div class="answers">'+q[1].map((o,j)=>'<label><input type="radio" name="q'+i+'" value="'+j+'" '+(state.quiz[i]===j?'checked':'')+'> '+o+'</label>').join("")+'</div><div class="feedback hidden"></div>';a.querySelectorAll("input").forEach(x=>x.onchange=e=>{state.quiz[i]=Number(e.target.value);state.quizDone=false;save()});$("#quizList").appendChild(a)});$("#result").classList.add("hidden")}
$("#grade").onclick=()=>{let score=0;quiz.forEach((q,i)=>{const card=document.querySelector('.qcard[data-i="'+i+'"]'),fb=card.querySelector(".feedback"),a=state.quiz[i];card.classList.remove("correct","incorrect");fb.className="feedback";if(a===q[2]){score++;card.classList.add("correct");fb.classList.add("ok");fb.textContent="Correcto. "+q[3]}else{card.classList.add("incorrect");fb.classList.add("bad");fb.textContent=(a===undefined?"Sin responder. ":"Incorrecto. ")+q[3]}});state.quizDone=true;save();const p=Math.round(score/20*100),msg=p>=85?"Muy buen dominio.":p>=65?"Buen nivel; revisa los fallos.":p>=50?"Base suficiente, pero conviene reforzar conceptos.":"Repasa antes de continuar.";$("#result").innerHTML="<b>"+score+" / 20</b><p>"+p+"% · "+msg+"</p>";$("#result").classList.remove("hidden");$("#result").scrollIntoView({behavior:"smooth"})};
$("#resetQuiz").onclick=()=>{if(confirm("¿Borrar respuestas del test?")){state.quiz={};state.quizDone=false;save();renderQuiz()}};
$("#resetAll").onclick=()=>{if(confirm("¿Borrar todo el progreso y respuestas?")){localStorage.removeItem(KEY);location.reload()}};
renderNav();progress();